[core] add scope updater components
airbnb/goji-js pull request #74
Opened 2021-03-31 04:19 UTC by cottom

2021-04-05 13:59 UTC, malash requested changes
Thanks @cottom for your PR. I think it's a good creation to solve update performance in GojiJS. But, there are several problems we have to resolve.

1. Could you please rename the component to `ScopedUpdater` ?
2. Use `sendUpdateData` to transform JSON data is not a good idea. I prefer to modify `pure` function to support this feature.
3. Advice to use `Map<ComponentInstance, Updates>` for `scopedUpdates`
4. Add test cases for this new feature.
5. [useRef](https://goji.js.org/docs/en/refs) may not work inside `ScopedUpdater`.
6. Did you try this component on all platforms ?

2021-04-05 14:01 UTC, malash commented on packages/webpack-plugin/templates/components/scroll-view.js.ejs
> +    c: {
Why this change ?

2021-04-05 14:03 UTC, malash commented on packages/core/src/reconciler/instance.ts
> +  public getParent() {
Useless function

2021-04-06 12:52 UTC, cottom commented on packages/webpack-plugin/templates/components/scroll-view.js.ejs
> +    c: {
unified all `nodes` properties

2021-04-06 17:08 UTC, cottom commented
> Thanks @cottom for your PR. I think it's a good creation to solve update performance in GojiJS. But, there are several problems we have to resolve.
> 
> 1. Could you please rename the component to `ScopedUpdater` ?
> 2. Use `sendUpdateData` to transform JSON data is not a good idea. I prefer to modify `pure` function to support this feature.
> 3. Advice to use `Map<ComponentInstance, Updates>` for `scopedUpdates`
> 4. Add test cases for this new feature.
> 5. [useRef](https://goji.js.org/docs/en/refs) may not work inside `ScopedUpdater`.
> 6. Did you try this component on all platforms ?

1. NIT, updated.
2. change pure is not easy to meet the demand of the feature and also break lots of test case. oervall pure is not a good practice here. Just leave it for later refractor.
3. NIT, updated.
4. updated.
5. updated.
6. Yes.

2021-04-07 14:15 UTC, malash commented on packages/webpack-plugin/templates/leaf-components.wxml.ejs
> +      <% if (component.isWrapped && !component.isSelfHost) { %>
isHostWrapped

2021-04-07 14:16 UTC, malash commented on packages/core/src/components/scopedUpdater.tsx
> +    ref,
No need to forward ref here

2021-04-07 14:17 UTC, malash commented on packages/core/src/components/scopedUpdater.tsx
> +  props: ScopedUpdaterProps,
Use `unsafe_className` and `unsafe_style`

2021-04-07 14:18 UTC, malash commented on packages/webpack-plugin/src/constants/components.ts
> +  return [
`['wechat', 'qq'].includes(target) ? [{ xxx }] : []`

2021-04-07 14:22 UTC, malash commented on packages/webpack-plugin/templates/leaf-components.wxml.ejs
> +        c="{{c}}"
Remove this line

2021-04-07 16:45 UTC, malash approved these changes

2021-04-12 08:45 UTC, merged